spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zbc
    password: 123456
    url: jdbc:mysql://localhost:3306/bookdb
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.springbootmanager.pojo
server:
  port: 8080
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  helper-dialect: mysql

